
import { SALOrderDetailCusDTO } from "./sal-order-detail.dto";
class SALOrderMasterDTO {
  Code: number = 0;
  ID: string = '';
  Customer: number;
  UserID: number | null;
  CustomerGender: number | null;
  Partner: number;
  SaleDate: Date | null;
  SaleStaff: number;
  IsNewCustomer: boolean;
  TechnicalStaff: number;
  AmountPaid: number = 0;
  PaymentMethod: number;
  PaymentCount: number = 0;
  HeadOut: number;
  WHOut: number;
  TypeData: number;
  Status: number = 1;
  CreateBy: string;
  CreateTime: Date | null;
  LastModifiedBy: string;
  LastModifiedTime: Date | null;
}

export class SALOrderMasterCusDTO extends SALOrderMasterDTO {
  StatusName: string = 'Tạo mới';
  RetailTypeData: number = 1;
  RetailTypeDataName: string = 'Mới';
  Email: string = '';
  TotalPrice: number = 0;
  TotalVehicle: number = 0;
  CustomerName: string = '';
  Phone: string = '';
  CustomerPhone: string = '';
  Address: string = '';
  SaleStaffName: string = '';
  PaymentMethodName: string = '';
  FullName: string = '';
  PartnerName: string = '';
  ListDetail: SALOrderDetailCusDTO[] = [];
  ListBuyVehicle: SALOrderDetailCusDTO[] = [];
  PartnerOccupationName: string = '';
  PartnerPhone: string = '';
  PartnerFullAddress: string = '';
  PartnerEmail: string = '';
  PartnerAddress: string = '';
  PartnerWardName: string = '';
  PartnerDistrictName: string = '';
  PartnerProvinceName: string = '';
  CustomerNeeds: string = '';
  CustomerCharacteristics: string = '';
  CustomerExpectation: string = '';
  CustomerPreferences: string = '';
  CustomerNotes: string = '';
  BookCount: number;
  TransferCount: number;
  BuyCount: number;
  OrderDetail: SALOrderDetailCusDTO;
  VehiclePrice: number = 0;
  VatPrice: number = 0;
  ServiceTotal: number = 0;
  PartTotal: number = 0;
  DiscountAmount: number = 0;
  TotalBeforeDiscount: number = 0;
  TotalPayment: number = 0;
  ListPaymentVehicle: SALOrderDetailCusDTO[] = [];
  NumOfReceipt: number = 0;
  NumOfInvoice: number = 0;
  ListService: [] = [];
  ListPart: [] = [];
  ListVehicle: [] = [];
  TypeOfVehicleName: string | null;
  VehicleName: string | null;
  VehicleColorName: string | null;
  ListCareVehicle: string[] | null;
  ListInvoiceSelection: SALOrderDetailCusDTO[] | null;
  OrderInvoice: number | null;
}