export enum KeyLocalStorageEnum {
  DLLPACKAGE = "dll_package",
  BEARER_TOKEN = 'bearer_token',
  USER_INFOR = 'user_info',
  HEAD_OBJECT = 'head_object',
  HEAD_LIST = 'head_list',
  INVENTORY_OBJECT = 'inventory_object',
  INV_POINT_OBJECT = 'inv_point_object',
  MODULE_ACTIVE = 'module_active',
  OUT_URL = 'out_url',
  IOMASTER_OBJECT = 'iomaster_object',
  TYPE_PART_OBJECT = 'type_part_object',
  PART_ITEM_OBJECT = 'part_item_object',
  USER_PERMISSION = 'user_permission',
  RETAIL = 'retail',
  WHOLESALE = 'wholesale',
  DO = 'delivery_order',
  INBOUND = 'inbound',
  WOM_MASTER = 'wom_master',
  WOM_SERVICE = 'wom_service',
  SAL_ORDER_RECEIPT = 'sal_order_receipt',
  SAL_ORDER_INVOICE = 'sal_order_invoice',
  SAL_ORDER_DETAIL = 'sal_order_detail',
  SAL_ORDER_MASTER = 'sal_order_master',
  LS_VEHICLE_COLOR = 'ls_vehicle_color',
}
